### ISSUE TITLE
[Bug] Signs Not Working Well

### ISSUE THREAD

**Issue by catter1** [Stardust-Labs-MC/StardustMC#10]
### Username

catter1

### Describe the issue

Signs for various things are not working too well. Not much more description needed.

**Comment by aisukuma** [comment]
- Signs are bugged due to EZ Chest Shop and ViaVersion. When a player on 1.20+ joins on a older server (a server running on 1.19.4 or lower) and tries to edit their hologram or shop prices immediately cancels out the sign GUI.
  - Because of this, any newly created signs will become empty after placing down
  - Text on signs will also disappear if you apply glow ink or a dye

- Players are unable to edit signs

**Comment by aisukuma** [comment]
The plugin has updated which fixes the disappearing sign text and also fixes users unable to edit shop prices/hologram text for their shops.
